In [1]:
import pandas as pd
data = pd.read_csv("student.csv")
data['result']

0       Pass
1       Fail
2       Pass
3       Pass
4     Absent
5       Fail
6       Fail
7       Pass
8       Pass
9     Absent
10      Pass
Name: result, dtype: str

In [ ]:
result_category = data['result']    #pandas series

In [3]:
from sklearn.preprocessing import LabelEncoder
obj = LabelEncoder()
result = obj.fit_transform(result_category)

In [4]:
result

array([2, 1, 2, 2, 0, 1, 1, 2, 2, 0, 2])

In [ ]:
from sklearn.preprocessing import LabelBinarizer
obj = LabelBinarizer()
result = obj.fit_transform(result_category)    

In [ ]:
result #converted to numerical values and using one hot encoding
#LabelEncoder------->LabelBinarizer

array([[0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1]])

In [ ]:
obj.classes_        #all categories
 

array(['Absent', 'Fail', 'Pass'], dtype='<U6')

In [ ]:
from sklearn.preprocessing import OneHotEncoder
# result = obj.fit_transform(result_category) OneHotEncoder will not accept a 1D array directly. You need to reshape it to 2D.
result_reshaped = result_category.values.reshape(-1, 1) # Convert pandas Series → NumPy 2D array
result_df = result_category.to_frame()  # method2: Convert the pandas Series to a DataFrame, which is 2D  

obj = OneHotEncoder(sparse_output=False)
# OneHotEncoder by default returns a sparse matrix Sparse matrices save memory when you have a lot of zeros (common in one-hot encoding), 
# but they don’t display like a normal array, not a normal NumPy array. You are telling it: “I don’t want a sparse matrix, give me a normal NumPy array instead.”

result_onehot = obj.fit_transform(result_reshaped)

result_onehot#converted to numerical values and using one hot encoding

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [13]:
result


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (11, 3)>